template: docker_container_down
      on: docker.container_state
   class: Errors
    type: Containers
component: Docker
chart labels: container_name=*
   units: status
   every: 10s
  lookup: average -10s of exited
    warn: $this > 0
   delay: down 1m multiplier 1.5 max 2h
 summary: Docker container ${label:container_name} down
    info: Docker container ${label:container_name} is currently not running
      to: sysadmin
